#!/bin/sh
#
# Copyright (c) 2017-2022, University of Tennessee. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# This program is free software: you can redistribute it and/or modify it under
# the terms of the BSD 3-Clause license. See the accompanying LICENSE file.
#
# Checks that HIP files have been updated using `hipify`
# when CUDA files are updated.

return=0

# Ensure md5 files exist and are up-to-date.
cu_files=src/cuda/*.cu
for cu in ${cu_files}; do
    md5_files="${md5_files} ${cu}.md5"
done
make -s ${md5_files}

for cu in ${cu_files}; do
    base=$(basename -- ${cu%%.*})
    hip=src/hip/${base}.hip.cc
    if diff ${cu}.md5 ${hip}.dep > /dev/null 2>&1; then
        #printf "%-40s up-to-date\n" "${hip}"
        :  # no-op
    else
        printf "%-40s out-of-date with ${cu}\n" "${hip}"
        return=2
    fi
done
if [ "${return}" -ne 0 ]; then
    printf "Run 'make hipify' and commit changes.\n"
    printf "Run 'touch src/cuda/*.cu' first if needed to force hipify.\n"
fi

# Comment out exit in .git/hooks/pre-push to check files but allow the push.
exit $return
