name: Spack

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slate_spack:
    timeout-minutes: 120
    strategy:
      matrix:
        device: [gpu_nvidia, gpu_amd, gpu_intel]
      fail-fast: false
#    runs-on: ${{ matrix.device }}
    steps:
      - uses: actions/checkout@v3
      - name: Spack Build
        run: .github/workflows/spack.sh build ${{matrix.device}}
      - name: Spack Test
        run: .github/workflows/spack.sh test ${{matrix.device}}
      - name: Spack Smoke Test
        run: .github/workflows/spack.sh smoke ${{matrix.device}}

